// Code generated by goctl. DO NOT EDIT!
// Source: gateway.proto

package server

import (
	"context"

	"github.com/tangbo/twatt/liyue/im/gateway/internal/logic"
	"github.com/tangbo/twatt/liyue/im/gateway/internal/svc"
	"github.com/tangbo/twatt/liyue/im/gateway/pb"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGatewayServer

	websocketSrv logic.WebsocketServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx:       svcCtx,
		websocketSrv: logic.NewWebsocketServer(svcCtx),
	}
}

func (s *GatewayServer) Greet(ctx context.Context, in *pb.GreetReq) (*pb.GreetResp, error) {
	l := logic.NewGreetLogic(ctx, s.svcCtx)
	return l.Greet(in)
}

func (s *GatewayServer) Listen() {
	s.websocketSrv.ListenAndServe()
}
