// Code generated by goctl. DO NOT EDIT!
// Source: im.proto

package server

import (
	"context"

	"github.com/tangbo/twatt/liyue/im/rpc/internal/logic"
	"github.com/tangbo/twatt/liyue/im/rpc/internal/svc"
	"github.com/tangbo/twatt/liyue/im/rpc/pb"
)

type ImServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImServer
}

func NewImServer(svcCtx *svc.ServiceContext) *ImServer {
	return &ImServer{
		svcCtx: svcCtx,
	}
}

func (s *ImServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
